#cloud-config
# Copyright (c) David Wettstein, licensed under the MIT License
# https://cloud-init.io/
# https://cloudinit.readthedocs.io/
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html

hostname: ${hostname}
local-hostname: ${hostname}
instance-id: ${instance_id}
# network:
#   version: 2
#   ethernets:
#     eth0:
#       dhcp4: true
# ssh_authorized_keys:
#   - Contents of `cat $HOME/.ssh/id_rsa.pub`
# users:
#   - name: root
#     lock-passwd: false
#     passwd: Output of `openssl passwd -6 -salt any_salt`
# bootcmd:
#   # Disable root password expiration (e.g. PhotonOS)
#   - /bin/sed -E -i 's/^root:([^:]+):.*$/root:\1:99999:0:99999:0:::/' /etc/shadow
final_message: "System successfully customized using cloud-init after $UPTIME seconds."
